export const CHARACTER_NAMES = [
  'Adrack Humble',
  'Alliser Thorne',
  'Alton Lannister',
  'Anguy the Archer',
  'Anya Waynwood',
  'Aremca',
  'Areo Hotah',
  'Arya Stark',
  'Asha Greyjoy',
  'Balerion',
  'Balon Greyjoy',
  'Barristan Selmy',
  'Benjen Stark',
  'Beric Dondarrion',
  'Biter',
  'Black Walder Frey',
  'Bran Stark',
  'Brienne of Tarth',
  'Bronn',
  'Brynden Tully',
  'Catelyn Stark',
  'Cersei Lannister',
  'Craster',
  'Daario Naharis',
  'Daenerys Targaryen',
  'Dagmer Cleftjaw',
  'Daisy',
  'Dareon',
  'Davos Seaworth',
  'Dontos Hollard',
  'Doran Martell',
  'Doreah',
  'Drowned Priest',
  'Dolorous Edd Tollett',
  'Eddard Stark',
  'Edmure Tully',
  'Ellaria Sand',
  'Galbart Glover',
  'Gared',
  'Gendry',
  'Gilly',
  'Grand Maester Pycelle',
  'Gregor Clegane',
  'Grenn',
  'Grey Worm',
  'Hallyne',
  'High Sparrow',
  'Hodor',
  'Hot Pie',
  'Hugh of the Vale',
  'Illyrio Mopatis',
  'Ilyn Payne',
  'Irri',
  'Jaime Lannister',
  'Janos Slynt',
  'Jaqen H’ghar',
  'Jeor Mormont',
  'Jhiqui',
  'Joffrey Baratheon',
  'Jojen Reed',
  'Jon Arryn',
  'Jon Snow',
  'Jon Umber',
  'Jonos Bracken',
  'Jorah Mormont',
  'Jory Cassel',
  'Kevan Lannister',
  'Khal Drogo',
  'Kovarro',
  'Kraznys',
  'Lady Whiskers',
  'Lancel Lannister',
  'Locke',
  'Lommy Greenhands',
  'Loras Tyrell',
  'Black Lorren',
  'Lysa Arryn',
  'Mace Tyrell',
  'Maester Aemon',
  'Maester Cressen',
  'Maester Luwin',
  'Maggy the Frog',
  'Mago',
  'Mance Rayder',
  'Margaery Tyrell',
  'Marillion',
  'Masha Heddle',
  'Matthos Seaworth',
  'Meera Reed',
  'Melisandre of Asshai',
  'Mero, Titan\'s Bastard',
  'Meryn Trant',
  'Mhaegen',
  'Mirri Maz Duur',
  'Missandei',
  'Mord',
  'Mossador',
  'Mycah',
  'Myrcella Baratheon',
  'Oberyn Martell',
  'Old Nan',
  'Olenna Tyrell',
  'Olly',
  'Olyver',
  'Orell',
  'Osha',
  'Petyr Baelish',
  'Podrick Payne',
  'Polliver',
  'Prendahl',
  'Pyat Pree',
  'Pypar',
  'Qhorin Halfhand',
  'Qotho',
  'Quaithe',
  'Qyburn',
  'Rakharo',
  'Ralf Kenning',
  'Ramsay Snow',
  'Rast',
  'Rattleshirt',
  'Renly Baratheon',
  'Rickard Karstark',
  'Rickon Stark',
  'Robb Stark',
  'Robert Baratheon',
  'Robin Arryn',
  'Rodrik Cassel',
  'Roose Bolton',
  'Rorge',
  'Ros',
  'Roslin Frey',
  'Salladhor Saan',
  'Samwell Tarly',
  'Sandor Clegane',
  'Sansa Stark',
  'Selyse Baratheon',
  'Septa Mordane',
  'Septa Unella',
  'Ser Pounce',
  'Shae',
  'Shagga',
  'Shireen Baratheon',
  'Stannis Baratheon',
  'Steelshanks',
  'Stiv',
  'Syrio Forel',
  'Talisa Maegyr',
  'The Spice King',
  'The Tickler',
  'Theon Greyjoy',
  'Thoros of Myr',
  'Timett son of Timett',
  'Tobho Mott',
  'Tommen Baratheon',
  'Tormund Giantsbane',
  'Trystane Martell',
  'Tycho Nestoris',
  'Tyrion Lannister',
  'Tywin Lannister',
  'Vardis Egan',
  'Varys',
  'Viserys Targaryen',
  'Walder Frey',
  'Waymar Royce',
  'Xaro Xhoan Daxos',
  'Ygritte',
  'Yohn Royce',
  'Yoren'
];
